name: testsuite

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:

  ubuntu:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Makefile.PL
        run: perl -I$(pwd) Makefile.PL
      - name: make test
        run: make test
      - name: prove xt
        run: prove -b xt

  linux:
    name: "linux ${{ matrix.perl-version }}"
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          [
            "latest",
            "5.30",
            "5.28",
            "5.26",
            "5.24",
            "5.22",
            "5.20-buster",
            "5.18-buster",
            "5.16-buster",
            "5.14-buster",
            "5.12-buster",
            "5.10-buster",
            "5.8-buster",
          ]

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Makefile.PL
        run: perl -I$(pwd) Makefile.PL
      - name: make test
        run: make test
      - name: load JSON::PP before Cpanel
        if: ${{ matrix.perl-version == 'latest' }}
        run: cpanm -n Cpanel::JSON::XS Test::Warnings && perl -Ilib -we 'use Test::More; use Test::Warnings qw(:report_warnings); use JSON::PP (); use Cpanel::JSON::XS (); done_testing'
      - name: load JSON::PP after Cpanel
        if: ${{ matrix.perl-version == 'latest' }}
        run: cpanm -n Cpanel::JSON::XS Test::Warnings && perl -Ilib -we 'use Test::More; use Test::Warnings qw(:report_warnings); use Cpanel::JSON::XS (); use JSON::PP (); done_testing'


  macOS:
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Makefile.PL
        run: perl -I$(pwd) Makefile.PL
      - name: make test
        run: make test

  # windows:
  #   needs: [ubuntu]
  #   env:
  #     PERL_USE_UNSAFE_INC: 0
  #     AUTHOR_TESTING: 0
  #     AUTOMATED_TESTING: 1
  #     RELEASE_TESTING: 0

  #   runs-on: windows-latest

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       perl-version: [latest]

  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Set up Perl
  #       run: |
  #         choco install strawberryperl
  #         echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
  #     - name: perl -V
  #       run: perl -V
  #     - name: Makefile.PL
  #       run: perl -I Makefile.PL
  #     - name: make test
  #       run: make test